# Generates backend/src/seeds/gems.data.ts from tunisia-travel-data.json:
#  - geocodes each gem via OpenStreetMap Nominatim (1 req/sec), with governorate-centroid fallback
#  - maps gem type -> existing app category name
#  - folds the photo credit into the description (license compliance)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$data = Get-Content (Join-Path $root 'tunisia-travel-data.json') -Raw | ConvertFrom-Json
$ua = @{ 'User-Agent' = 'e-tunisia-travel-seed/1.0 (contact: craftlord34@gmail.com)' }

$catOf = @{
  'cafe'='Gastronomy'; 'food-port'='Gastronomy';
  'craft-village'='Artisanat'; 'craft-town'='Artisanat'; 'souk'='Artisanat'; 'market'='Artisanat'; 'museum'='Artisanat';
  'beach'='Nature & Beaches'; 'oasis'='Nature & Beaches'; 'viewpoint'='Nature & Beaches'; 'mountain-hike'='Nature & Beaches';
  'national-park'='Nature & Beaches'; 'mountain-oasis'='Nature & Beaches'; 'thermal-springs'='Nature & Beaches'; 'coast'='Nature & Beaches';
  'mountain-village'='Nature & Beaches'; 'nature'='Nature & Beaches'; 'remote-island'='Nature & Beaches'; 'seaside-oasis'='Nature & Beaches';
  'salt-lake'='Nature & Beaches'; 'natural-landmark'='Nature & Beaches'; 'canyon'='Nature & Beaches'; 'desert-gateway'='Nature & Beaches';
  'desert-oasis'='Nature & Beaches'; 'desert-village'='Nature & Beaches'; 'fishing-village'='Nature & Beaches'; 'island'='Nature & Beaches';
  'island-reserve'='Nature & Beaches'; 'lagoon-heritage'='Nature & Beaches'; 'mountain-town'='Nature & Beaches'; 'wetland'='Nature & Beaches';
  'fort-beach'='Nature & Beaches'; 'old-port'='Nature & Beaches'; 'coast-town'='Nature & Beaches'; 'oasis-town'='Nature & Beaches'
  # everything else falls through to Historical Sites
}
$govCentroid = @{
  'Tunis'=@(36.806,10.181); 'Ben Arous'=@(36.66,10.32); 'Zaghouan'=@(36.40,10.14); 'Nabeul'=@(36.45,10.74);
  'Bizerte'=@(37.27,9.87); 'Beja'=@(36.73,9.18); 'Jendouba'=@(36.50,8.78); 'Kef'=@(36.17,8.70);
  'Siliana'=@(36.08,9.37); 'Sousse'=@(35.83,10.63); 'Monastir'=@(35.78,10.83); 'Mahdia'=@(35.50,11.06);
  'Kairouan'=@(35.68,10.10); 'Sfax'=@(34.74,10.76); 'Gabes'=@(33.88,10.10); 'Kebili'=@(33.70,8.97);
  'Tozeur'=@(33.92,8.13); 'Medenine'=@(33.35,10.50); 'Tataouine'=@(32.93,10.45)
}
# featured (region-representative hidden gems)
$featured = @(17,19,22,31,34,48,54,64,82,84,86,90,99,102,110,120)
# geocoding query overrides where the display name is a poor search term
$geoQ = @{ 1='Souk des Chechias, Tunis'; 4='Zaytuna Mosque, Tunis'; 7='Sidi Bou Said'; 11='La Marsa';
  77='Tozeur'; 80='Nefta'; 88='Chott el Gharsa'; 117='Houmt Souk, Djerba'; 120='Galite, Bizerte' }

function CleanQ([string]$n){ $c = $n -replace '\s*\(.*?\)',''; $c = ($c -split ' & ')[0]; $c.Trim() }

$titleCase = { param($s) ($s -split '-' | ForEach-Object { if($_){$_.Substring(0,1).ToUpper()+$_.Substring(1)} }) -join ' ' }

$out = New-Object System.Collections.ArrayList
$geo=0; $fb=0
foreach($g in $data.gems){
  $lat=$null; $lon=$null
  $q = if($geoQ.ContainsKey([int]$g.id)){ $geoQ[[int]$g.id] } else { (CleanQ $g.name) + ', Tunisia' }
  try{
    $eq=[uri]::EscapeDataString($q)
    $u="https://nominatim.openstreetmap.org/search?q=$eq&format=json&limit=1&countrycodes=tn"
    $r=Invoke-RestMethod -Uri $u -Headers $ua -TimeoutSec 25
    if($r -and $r.Count -ge 1){ $lat=[double]$r[0].lat; $lon=[double]$r[0].lon; $geo++ }
  } catch {}
  if($null -eq $lat){
    $c = $govCentroid[$g.governorate]; if(-not $c){ $c=@(34.0,9.0) }
    $j = ([int]$g.id % 17) / 100.0    # small deterministic jitter so points don't stack
    $lat = $c[0] + $j - 0.085; $lon = $c[1] + (([int]$g.id % 13)/100.0) - 0.065; $fb++
  }
  $cat = if($catOf.ContainsKey($g.type)){ $catOf[$g.type] } else { 'Historical Sites' }
  $typeRead = & $titleCase $g.type
  $credit = if($g.image.author){ $g.image.author } else { 'Wikimedia Commons' }
  $lic = if($g.image.license){ $g.image.license } else { 'see source' }
  $desc = $g.description
  if($g.tip){ $desc = "$desc Insider tip: $($g.tip)" }
  $desc = "$desc `u{00B7} Photo: $credit ($lic), via Wikimedia Commons."
  [void]$out.Add([ordered]@{
    name        = $g.name
    description = $desc
    address     = "$($g.governorate), Tunisia"
    city        = $g.governorate
    governorate = $g.governorate
    latitude    = [math]::Round($lat,6)
    longitude   = [math]::Round($lon,6)
    coverImage  = $g.image.thumb
    images      = @($g.image.full, $g.image.thumb)
    tags        = @($typeRead, 'Hidden Gem')
    categoryName= $cat
    isFeatured  = [bool]($featured -contains [int]$g.id)
    sourcePage  = $g.image.sourcePage
  })
  Start-Sleep -Milliseconds 1100   # Nominatim politeness: <= 1 req/sec
}

$json = ($out | ConvertTo-Json -Depth 6)
$ts = @"
// AUTO-GENERATED by travel-content/gen-gems-seed.ps1 — do not edit by hand.
// 120 Tunisian hidden gems: geocoded coordinates + real Wikimedia Commons photos.
// Photo credit is folded into each description for license attribution.

export interface GemSeed {
  name: string;
  description: string;
  address: string;
  city: string;
  governorate: string;
  latitude: number;
  longitude: number;
  coverImage: string;
  images: string[];
  tags: string[];
  categoryName: string;
  isFeatured: boolean;
  sourcePage: string;
}

export const gemsData: GemSeed[] = $json;
"@
$dest = Join-Path $root '..\backend\src\seeds\gems.data.ts'
Set-Content -Path $dest -Value $ts -Encoding UTF8
"wrote $dest"
"geocoded: $geo   centroid-fallback: $fb   total: $($out.Count)"
