export const morePlacesData = [
  // ──── HISTORICAL & MONUMENTS ────
  {
      name: 'Bulla Regia',
      nameFr: 'Bulla Regia',
      nameAr: 'بولا ريجيا',
      slug: 'bulla-regia',
      description: 'An extraordinary ancient Roman city featuring unique underground villas built to escape the summer heat, complete with pristine floor mosaics.',
      address: 'Route de Jendouba',
      city: 'Jendouba',
      governorate: 'Jendouba',
      latitude: 36.5594,
      longitude: 8.7561,
      coverImage: 'https://images.unsplash.com/photo-1548682913-75c13e6d2cb1?w=800',
      tags: ['Roman', 'Ruins', 'Underground', 'Mosaics'],
      rating: 4.8,
      reviewCount: 420,
      viewCount: 4100,
      categorySlug: 'monuments-histoire',
  },
  {
      name: 'Sbeitla (Sufetula)',
      nameFr: 'Vestiges de Sbeïtla',
      nameAr: 'سبيطلة',
      slug: 'sbeitla-ruins',
      description: 'The golden ruins of Sufetula feature incredibly preserved twin temples of Jupiter, Juno, and Minerva, making it one of the finest Roman sites in North Africa.',
      address: 'Sbeitla',
      city: 'Sbeitla',
      governorate: 'Kasserine',
      latitude: 35.2404,
      longitude: 9.1232,
      coverImage: 'https://images.unsplash.com/photo-1627581909893-fd4ccbb4fa4d?w=800',
      tags: ['Roman Temples', 'History', 'Ruins', 'Architecture'],
      rating: 4.7,
      reviewCount: 310,
      viewCount: 3890,
      categorySlug: 'monuments-histoire',
  },
  {
      name: 'Dougga (Thugga)',
      nameFr: 'Cité romaine de Dougga',
      nameAr: 'دقة',
      slug: 'dougga-thugga',
      description: 'A UNESCO World Heritage site and famously one of the best-preserved Roman small towns in North Africa. Overlooks the lush Oued Khalled valley.',
      address: 'Teboursouk',
      city: 'Testour',
      governorate: 'Béja',
      latitude: 36.4225,
      longitude: 9.2197,
      coverImage: 'https://images.unsplash.com/photo-1572204292164-b35ba943fca7?w=800',
      tags: ['UNESCO', 'Roman Town', 'Capitol', 'Amphitheater'],
      rating: 4.9,
      reviewCount: 940,
      viewCount: 11000,
      categorySlug: 'monuments-histoire',
  },
  {
      name: 'Great Mosque of Kairouan',
      nameFr: 'Grande Mosquée de Kairouan',
      nameAr: 'جامع القيروان الأكبر',
      slug: 'kairouan-mosque',
      description: 'One of the oldest and most important mosques in the Islamic world. A sprawling courtyard of marble and monumental arches spanning back to 670 AD.',
      address: 'Rue de la Mosquée',
      city: 'Kairouan',
      governorate: 'Kairouan',
      latitude: 35.6814,
      longitude: 10.1039,
      coverImage: 'https://images.unsplash.com/photo-1594818379496-da1e345b0ded?w=800',
      tags: ['Islamic', 'Architecture', 'Spiritual', 'Mosque'],
      rating: 4.9,
      reviewCount: 1120,
      viewCount: 14500,
      categorySlug: 'monuments-histoire',
  },
  {
      name: 'Zaghouan Water Temple',
      nameFr: 'Temple des Eaux de Zaghouan',
      nameAr: 'معبد المياه بزغوان',
      slug: 'zaghouan-water-temple',
      description: 'Built during Emperor Hadrian’s reign around the natural spring that fed all of Carthage through a massive 132km aqueduct.',
      address: 'Jebel Zaghouan',
      city: 'Zaghouan',
      governorate: 'Zaghouan',
      latitude: 36.3916,
      longitude: 10.1340,
      coverImage: 'https://images.unsplash.com/photo-1627581909893-fd4ccbb4fa4d?w=800',
      tags: ['Roman', 'Aqueduct', 'Spring', 'Temple'],
      rating: 4.6,
      reviewCount: 220,
      viewCount: 2900,
      categorySlug: 'monuments-histoire',
  },

  // ──── NATURE & ADVENTURE ────
  {
      name: 'Matmata Troglodyte Village',
      nameFr: 'Maisons Troglodytes de Matmata',
      nameAr: 'مطماطة',
      slug: 'matmata-troglodyte',
      description: 'Famous underground troglodyte structures built into craters on the desert floor. Star Wars fans will recognize this as the home of Luke Skywalker on Tatooine.',
      address: 'Matmata',
      city: 'Matmata',
      governorate: 'Gabès',
      latitude: 33.5415,
      longitude: 9.9676,
      coverImage: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
      tags: ['Star Wars', 'Caves', 'Underground', 'Desert'],
      rating: 4.8,
      reviewCount: 880,
      viewCount: 9200,
      categorySlug: 'nature-aventure',
  },
  {
      name: 'Ichkeul National Park',
      nameFr: 'Parc National de l\'Ichkeul',
      nameAr: 'الحديقة الوطنية بإشكل',
      slug: 'ichkeul-national-park',
      description: 'A UNESCO Biosphere Reserve and vital stopover for hundreds of thousands of migrating birds. Features a beautiful lake and lush marshlands.',
      address: 'Route de Mateur',
      city: 'Mateur',
      governorate: 'Bizerte',
      latitude: 37.1667,
      longitude: 9.6667,
      coverImage: 'https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800',
      tags: ['Nature', 'UNESCO', 'Lake', 'Birdwatching'],
      rating: 4.7,
      reviewCount: 450,
      viewCount: 5200,
      categorySlug: 'nature-aventure',
  },
  {
      name: 'Oued Zitoun Waterfalls',
      nameFr: 'Cascades d\'Oued Zitoun',
      nameAr: 'شلالات وادي الزيتون',
      slug: 'oued-zitoun-waterfalls',
      description: 'A spectacular hidden gem in northern Tunisia. Plunging waterfalls surrounded by lush greenery, perfect for an adventurous day hike.',
      address: 'Oued Zitoun',
      city: 'Bizerte',
      governorate: 'Bizerte',
      latitude: 37.0423,
      longitude: 9.2078,
      coverImage: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
      tags: ['Waterfalls', 'Hiking', 'Nature', 'Forest'],
      rating: 4.8,
      reviewCount: 320,
      viewCount: 3900,
      categorySlug: 'nature-aventure',
  },
  {
      name: 'Cap Blanc & Bizerte Coast',
      nameFr: 'Cap Blanc Bizerte',
      nameAr: 'الرأس الأبيض ببنزرت',
      slug: 'cap-blanc-bizerte',
      description: 'The northernmost point of Africa. Spectacular rocky cliffs diving into the sapphire blue Mediterranean Sea. Exceptional hiking and views.',
      address: 'Corniche de Bizerte',
      city: 'Bizerte',
      governorate: 'Bizerte',
      latitude: 37.3392,
      longitude: 9.8519,
      coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      tags: ['Cliffs', 'Ocean', 'Hiking', 'Wild Nature'],
      rating: 4.9,
      reviewCount: 230,
      viewCount: 2700,
      categorySlug: 'nature-aventure',
  },

  // ──── CULTURE & MUSEUMS ────
  {
      name: 'Djerbahood (Erriadh)',
      nameFr: 'Djerbahood, Village Street Art',
      nameAr: 'جربة هود',
      slug: 'djerbahood-street-art',
      description: 'An open-air museum of street art in the traditional village of Erriadh, Djerba. Artists from around the world have painted beautiful murals merging modern art with traditional architecture.',
      address: 'Erriadh Village',
      city: 'Houmt Souk',
      governorate: 'Medenine',
      latitude: 33.8211,
      longitude: 10.8524,
      coverImage: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
      tags: ['Street Art', 'Village', 'Culture', 'Museum'],
      rating: 4.8,
      reviewCount: 610,
      viewCount: 8800,
      categorySlug: 'musees-culture',
  },
  {
      name: 'Takrouna Berber Village',
      nameFr: 'Village Berbère de Takrouna',
      nameAr: 'تكرونة',
      slug: 'takrouna-berber-village',
      description: 'A traditional Berber village perched precariously on a large rocky crag of fossilized rock. Stunning panoramas over the Gulf of Hammamet and Mount Zaghouan.',
      address: 'Takrouna Mountain',
      city: 'Enfidha',
      governorate: 'Sousse',
      latitude: 36.1432,
      longitude: 10.3340,
      coverImage: 'https://images.unsplash.com/photo-1548682913-75c13e6d2cb1?w=800',
      tags: ['Berber', 'Village', 'Mountain', 'Views'],
      rating: 4.7,
      reviewCount: 210,
      viewCount: 3100,
      categorySlug: 'musees-culture',
  },
  {
      name: 'Bardo National Museum',
      nameFr: 'Musée National du Bardo',
      nameAr: 'المتحف الوطني بباردو',
      slug: 'bardo-national-museum',
      description: 'Located in an old beylical palace, this museum houses the world\'s most renowned collection of Roman mosaics alongside Punic and Islamic artifacts.',
      address: 'Bardo Palace',
      city: 'Tunis',
      governorate: 'Tunis',
      latitude: 36.8093,
      longitude: 10.1343,
      coverImage: 'https://images.unsplash.com/photo-1572204292164-b35ba943fca7?w=800',
      tags: ['Museum', 'Roman Mosaics', 'Palace', 'Antiquity'],
      rating: 4.9,
      reviewCount: 1540,
      viewCount: 22000,
      categorySlug: 'musees-culture',
  },

  // ──── GASTRONOMIC & PLACES ────
  {
      name: 'Cafe des Nattes (Sidi Bou Said)',
      nameFr: 'Café des Nattes',
      nameAr: 'قهوة العالية',
      slug: 'cafe-des-nattes',
      description: 'Sidi Bou Said\'s iconic hilltop cafe renowned for its mint tea with pine nuts and historic Moorish architecture. A quintessential Tunisian experience.',
      address: 'Place de Sidi Bou Said',
      city: 'Carthage',
      governorate: 'Tunis',
      latitude: 36.8711,
      longitude: 10.3475,
      coverImage: 'https://images.unsplash.com/photo-1548682913-75c13e6d2cb1?w=800',
      tags: ['Cafe', 'Tea', 'Traditional', 'Seaview'],
      rating: 4.7,
      reviewCount: 1890,
      viewCount: 25000,
      categorySlug: 'gastronomie',
  },
  {
      name: 'Medina of Tunis Souks',
      nameFr: 'Souks de la Médina de Tunis',
      nameAr: 'أسواق مدينة تونس',
      slug: 'medina-tunis-souks',
      description: 'A labyrinth of covered streets specializing in perfumes (Souk el Attarine), carpets, and jewelry. The bustling heart of traditional Tunis craftsmanship.',
      address: 'Medina',
      city: 'Tunis',
      governorate: 'Tunis',
      latitude: 36.7975,
      longitude: 10.1711,
      coverImage: 'https://images.unsplash.com/photo-1594818379496-da1e345b0ded?w=800',
      tags: ['Medina', 'Souk', 'Shopping', 'Tradition'],
      rating: 4.8,
      reviewCount: 2200,
      viewCount: 31000,
      categorySlug: 'artisanat-shopping',
  },
  {
      name: 'Korbous Thermal Baths',
      nameFr: 'Station Thermale de Korbous',
      nameAr: 'قربص',
      slug: 'korbous-thermal-baths',
      description: 'A spectacular cliffside town where 60°C hot springs flow directly into the sea creating a natural steaming spa environment with endless coastal views.',
      address: 'Cap Bon Peninsula',
      city: 'Korbous',
      governorate: 'Nabeul',
      latitude: 36.8183,
      longitude: 10.5701,
      coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      tags: ['Spa', 'Hot Springs', 'Wellness', 'Ocean'],
      rating: 4.7,
      reviewCount: 410,
      viewCount: 6500,
      categorySlug: 'nature-aventure',
  }
];
